namespace:
  create: false
  name: techchallenge2

replicaCount: 2

image:
  repository: 258083582548.dkr.ecr.us-east-2.amazonaws.com/techchallenge2-app
  tag: "d88b97e882e1b0d45391e62d7880145e6c3c9091"
  pullPolicy: IfNotPresent

container:
  port: 5000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

probes:
  readiness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  liveness:
    path: /
    initialDelaySeconds: 15
    periodSeconds: 20

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

ingress:
  enabled: true
  className: alb
  path: /
  pathType: Prefix
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  scaleDownStabilizationWindowSeconds: 60
